plugins:
  - bsmu.biocell.plugins.gui.main_window.BiocellMainWindowPlugin:
      replace: bsmu.vision.plugins.windows.main.MainWindowPlugin
      alias: main_window

  - bsmu.vision.plugins.file_dropper.FileDropperPlugin
  - bsmu.vision.plugins.readers.image.common.CommonImageFileReaderPlugin
  - bsmu.vision.plugins.readers.image.wsi.WholeSlideImageFileReaderPlugin

  - bsmu.vision.plugins.postread.image_to_layered.ImageToLayeredImagePostReadConverterPlugin

  - bsmu.vision.plugins.visualizers.image.flat.FlatImageVisualizerPlugin
  - bsmu.vision.plugins.visualizers.image.layered.LayeredImageVisualizerPlugin

  - bsmu.vision.plugins.overlayers.image.ImageViewerOverlayerPlugin
#  - bsmu.vision.plugins.overlayers.path.ImageViewerPathOverlayerPlugin
#  - bsmu.vision.plugins.overlayers.intersection.ImageViewerIntersectionOverlayerPlugin

  - bsmu.vision.plugins.writers.image.common.CommonImageFileWriterPlugin

  - bsmu.vision.plugins.tools.viewer.manager.ViewerToolManagerPlugin
  - bsmu.vision.plugins.tools.viewer.image.hand_tool.HandImageViewerToolPlugin
  - bsmu.biocell.plugins.tools.hed_wsi_smart_brush.HedSmartBrushImageViewerToolPlugin

  - bsmu.biocell.plugins.gui.pca_segmenter.PcaSegmenterGuiPlugin
  - bsmu.biocell.plugins.gui.pca_dir_segmenter.PcaDirSegmenterGuiPlugin
#  - bsmu.biocell.plugins.gui.tissue_dnn_segmenter.TissueDnnSegmenterGuiPlugin
#  - bsmu.biocell.plugins.gui.tissue_threshold_segmenter.TissueThresholdSegmenterGuiPlugin
#  - bsmu.biocell.plugins.kidney_tissue_segmenter.KidneyTissueSegmenterPlugin

#  - bsmu.vision.plugins.walkers.file.MdiImageLayerFileWalkerPlugin

  - bsmu.vision.plugins.layer_controller.MdiImageViewerLayerControllerPlugin
  - bsmu.vision.plugins.layers_view.LayersTableViewPlugin

  - bsmu.vision.plugins.task_storage_view.TaskStorageViewPlugin
