tissue_segmenter_model:
  name: '2024.10.17-v7-segformer-tu-resnetv2_50x1_bit.goog_distilled_in1k-panda+empty(512, 512)[(255,)].onnx'
  output_object_name: 'Tissue'
  output_object_short_name: 'T'
  preload: false
  batch_size: 10
  input_size: [3, 512, 512]
  channels_axis: 0
  channels_order: 'rgb'
  normalize: false
  preprocessing_mode: ''
  mask_binarization_threshold: 0.619
