tissue_segmenter_model:  # Trained on patches at 5x magnification
  path: 'dnn-models/tissue-v4-segformer-sum-tu-resnetv2_50x1_bit.goog_distilled_in1k-panda+empty(384, 384)[()].onnx'
  output_object_name: 'Tissue'
  output_object_short_name: 'T'
  preload: false
  batch_size: 12
  input_size: [3, 384, 384]
  channels_axis: 0
  channels_order: 'rgb'
  normalize: false
  preprocessing_mode: ''
  output_class_names: 'non_tissue'
  mask_binarization_thresholds: -0.2  # -0.8473  # Threshold raised to prevent tissue under-segmentation


#tissue_segmenter_model:  # Trained on patches at 5x, 2.5x, 1.25x, and 0.625x magnifications
#  path: 'dnn-models/tissue-v2-segformer-sum-tu-resnetv2_50x1_bit.goog_distilled_in1k-panda+empty(384, 384)[()].onnx'
#  output_object_name: 'Tissue'
#  output_object_short_name: 'T'
#  preload: false
#  batch_size: 12
#  input_size: [3, 384, 384]
#  channels_axis: 0
#  channels_order: 'rgb'
#  normalize: false
#  preprocessing_mode: ''
#  output_class_names: 'non_tissue'
#  mask_binarization_thresholds: 0.20067
