gleason_3_segmenter_model:  # trained on Gleason >= 3
  name: '2024.07.31-v6-segformer-tu-edgenext-small-panda-empty-512x512-gl3.onnx'
  output_object_name: 'Prostate Cancer Gleason >= 3'
  output_object_short_name: 'PCa G>=3'
  preload: false
  batch_size: 10
  input_size: [3, 512, 512]
  channels_axis: 0
  channels_order: 'rgb'
  normalize: false
  preprocessing_mode: 'image-net-torch'
  mask_binarization_threshold: 1.7346

gleason_4_segmenter_model:  # trained on Gleason >= 4
  name: '2024.07.31-v6-segformer-tu-edgenext-small-panda-empty-512x512-gl4.onnx'
  output_object_name: 'Prostate Cancer Gleason >= 4'
  output_object_short_name: 'PCa G>=4'
  preload: false
  batch_size: 10
  input_size: [3, 512, 512]
  channels_axis: 0
  channels_order: 'rgb'
  normalize: false
  preprocessing_mode: 'image-net-torch'
  mask_binarization_threshold: 0.6190
